version: '2'

services:
  identity-server:
    build: .
    volumes:
      - code_volume:/identity-server
    ports:
      - 8095:8081
    restart: on-failure
    depends_on:
      - mysql-development
    networks:
      - backend
    environment:
      ENV: "prod"
      CONFIG_FILE: "etc/config.yaml"
  identity-server-test:
    build: .
    volumes:
      - code_volume:/identity-server
    ports:
      - 8088:8081
    restart: on-failure
    networks:
      - backend
    environment:
      ENV: "test"
      CONFIG_FILE: "etc/config_test.yaml"

  mysql-development:
    build: ./MySQL
    environment:
      MYSQL_USER: "root"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: identity_db
    ports:
      - "3308:3306"
    networks:
      - backend
    volumes:
      - ./MySQL/init.sql:/docker-entrypoint-initdb.d/init.sql
      - named_volume:/var/lib/mysql
      - sqlite_volume:/var/tmp

networks:
  backend:
    driver: bridge
volumes:
  init: {}
  named_volume: {}
  code_volume: {}
  sqlite_volume: {}