version: '3'
services:
  db:
    build:
      context: db/
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: identity-server
      MYSQL_USER: identity
      MYSQL_PASSWORD: identity
    container_name: identity-db
    volumes:
      - .:/docker-entrypoint-initdb.d/
    ports:
      - "3306:3306"
    tty: true
  app:
    build:
      context: .
    volumes:
      - .:/go
    container_name: identity-server
    ports:
      - 8081:8081
    tty: true
    depends_on:
      - db