version: '3'

services:
  identity-server:
    build: .
    volumes:
      - code_volume:/identity-server
    ports:
      - 8095:8081
    restart: on-failure
    depends_on:
      - mysql-development
    networks:
      - backend

  mysql-development:
    build: ./MySQL
    environment:
      MYSQL_USER: "root"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: identity_db
    ports:
      - "3308:3306"
    networks:
      - backend
    volumes:
      - ./MySQL/init.sql:/docker-entrypoint-initdb.d/init.sql
      - named_volume:/var/lib/mysql

networks:
  backend:
    driver: bridge
volumes:
  init: {}
  named_volume: {}
  code_volume: {}