CREATE TABLE IF NOT EXISTS
    login_tokens (
    id VARCHAR(64) PRIMARY KEY,
    user_id  VARCHAR(100),
    token VARCHAR(600),
    ttl VARCHAR(120),
    expiry DATETIME,
    last_used DATETIME,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP)
    ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
