CREATE TABLE IF NOT EXISTS 
	identity_users (
    id VARCHAR(64) PRIMARY KEY,
	first_name  VARCHAR(100),
	last_name VARCHAR(100),
	email VARCHAR(120),
	password VARCHAR(500),
	company VARCHAR(64),
	post_code VARCHAR(64),
    terms INTEGER,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP)
    ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
