package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"strconv"

	jwt "github.com/golang-jwt/jwt/v5"
	"github.com/riyadennis/identity-server/app/gql/graph/generated"
	"github.com/riyadennis/identity-server/app/gql/graph/model"
	"github.com/riyadennis/identity-server/business"
	"github.com/riyadennis/identity-server/business/store"
	"github.com/riyadennis/identity-server/business/validation"
	"github.com/riyadennis/identity-server/foundation/middleware"
)

// Login is the resolver for the Login field.
func (r *mutationResolver) Login(ctx context.Context, input model.LoginInput) (*model.LoginResponse, error) {
	r.Logger.Info("processing graphql request to login")

	helper := business.NewHelper(r.Store, r.Authenticator, r.Logger)
	token, err := helper.Login(ctx, r.tokenConfig, *input.Email, *input.Password)
	if err != nil {
		return nil, err
	}

	status := http.StatusOK
	ttl, err := strconv.ParseInt(token.TokenTTL, 10, 32)
	if err != nil {
		return nil, err
	}
	intTTL := int(ttl)
	return &model.LoginResponse{
		Status:      &status,
		AccessToken: &token.AccessToken,
		Expiry:      &token.Expiry,
		TokenType:   &token.TokenType,
		LastRefresh: &token.LastRefresh,
		TokenTTL:    &intTTL,
	}, nil
}

// Register is the resolver for the Register field.
func (r *mutationResolver) Register(ctx context.Context, input model.RegisterInput) (*model.RegisterResponse, error) {
	r.Logger.Info("processing graphql request to register")

	u := &store.User{
		FirstName: input.FirstName,
		LastName:  input.LastName,
		Email:     input.Email,
		Password:  input.Password,
		Terms:     input.Terms,
	}
	if input.Company != nil {
		u.Company = *input.Company
	}
	if input.PostCode != nil {
		u.PostCode = *input.PostCode
	}

	if err := validation.ValidateUser(u); err != nil {
		return nil, err
	}

	existing, err := r.Store.Read(ctx, u.Email)
	if err != nil {
		return nil, err
	}
	if existing.Email == u.Email {
		return nil, errors.New("email already exists")
	}

	u.Password, err = business.EncryptPassword(u.Password)
	if err != nil {
		return nil, err
	}

	created, err := r.Store.Insert(ctx, u)
	if err != nil {
		return nil, err
	}

	status := http.StatusCreated
	_ = status
	return &model.RegisterResponse{
		ID:        &created.ID,
		FirstName: &created.FirstName,
		LastName:  &created.LastName,
		Email:     &created.Email,
		Company:   &created.Company,
		PostCode:  &created.PostCode,
		Terms:     &created.Terms,
		CreatedAt: &created.CreatedAt,
	}, nil
}

// AssignRole is the resolver for the assignRole field.
func (r *mutationResolver) AssignRole(ctx context.Context, userID string, role model.Role) (*model.RoleResponse, error) {
	r.Logger.Infof("assigning role %s to user %s", role, userID)

	if err := r.Store.UpdateRole(ctx, userID, role.String()); err != nil {
		return nil, fmt.Errorf("failed to assign role: %w", err)
	}

	return &model.RoleResponse{
		UserID: userID,
		Role:   role,
	}, nil
}

// Me is the resolver for the me query.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	accessToken, ok := ctx.Value(middleware.AccessTokenKey).(string)
	if !ok || accessToken == "" {
		return nil, fmt.Errorf("unauthorized: no access token provided")
	}
	claims, ok := ctx.Value(middleware.UserClaimsKey).(*jwt.RegisteredClaims)
	user, err := r.Store.Retrieve(ctx, claims.Subject)
	if err != nil {
		return nil, err
	}

	if user == nil {
		return nil, fmt.Errorf("failed to find user for ID %s", claims.Subject)
	}

	fullName := user.FirstName + " " + user.LastName
	return &model.User{
		ID:            claims.Subject,
		Email:         user.Email,
		Name:          &fullName,
		Picture:       nil,
		EmailVerified: false,
	}, nil
}

// GetUserRole is the resolver for the getUserRole field.
func (r *queryResolver) GetUserRole(ctx context.Context, userID string) (*model.RoleResponse, error) {
	r.Logger.Infof("fetching role for user %s", userID)

	user, err := r.Store.Retrieve(ctx, userID)
	if err != nil {
		return nil, fmt.Errorf("failed to retrieve user: %w", err)
	}
	if user == nil {
		return nil, fmt.Errorf("user %s not found", userID)
	}

	role := model.Role(user.Role)
	if !role.IsValid() {
		return nil, fmt.Errorf("invalid role %q for user %s", user.Role, userID)
	}

	return &model.RoleResponse{
		UserID: userID,
		Role:   role,
	}, nil
}

// ListUsersByRole is the resolver for the listUsersByRole field.
func (r *queryResolver) ListUsersByRole(ctx context.Context, role model.Role) ([]*model.User, error) {
	r.Logger.Infof("listing users with role %s", role)

	users, err := r.Store.ListByRole(ctx, role.String())
	if err != nil {
		return nil, fmt.Errorf("failed to list users by role: %w", err)
	}

	result := make([]*model.User, 0, len(users))
	for _, u := range users {
		fullName := u.FirstName + " " + u.LastName
		result = append(result, &model.User{
			ID:            u.ID,
			Email:         u.Email,
			Name:          &fullName,
			EmailVerified: false,
		})
	}
	return result, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
