package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"context"
	"fmt"
	"net/http"
	"strconv"

	"github.com/golang-jwt/jwt/v5"
	"github.com/riyadennis/identity-server/app/gql/graph/generated"
	"github.com/riyadennis/identity-server/app/gql/graph/model"
	"github.com/riyadennis/identity-server/business"
	"github.com/riyadennis/identity-server/foundation/middleware"
)

// Login is the resolver for the Login field.
func (r *mutationResolver) Login(ctx context.Context, input model.LoginInput) (*model.LoginResponse, error) {
	r.Logger.Info("processing graphql request to login")

	helper := business.NewHelper(r.Store, r.Authenticator, r.Logger)
	token, err := helper.Login(ctx, r.tokenConfig, *input.Email, *input.Password)
	if err != nil {
		return nil, err
	}

	status := http.StatusOK
	ttl, err := strconv.ParseInt(token.TokenTTL, 10, 32)
	if err != nil {
		return nil, err
	}
	intTTL := int(ttl)
	return &model.LoginResponse{
		Status:      &status,
		AccessToken: &token.AccessToken,
		Expiry:      &token.Expiry,
		TokenType:   &token.TokenType,
		LastRefresh: &token.LastRefresh,
		TokenTTL:    &intTTL,
	}, nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	accessToken, ok := ctx.Value(middleware.AccessTokenKey).(string)
	r.Logger.Infof("accesstoken from resolver: %v", accessToken)
	if !ok || accessToken == "" {
		return nil, fmt.Errorf("unauthorized: no access token provided")
	}
	claims, ok := ctx.Value(middleware.UserClaimsKey).(*jwt.RegisteredClaims)
	user, err := r.Store.Retrieve(ctx, claims.Subject)
	if err != nil {
		return nil, err
	}
	
	if user == nil {
		return nil, fmt.Errorf("failed to find user for ID %s", claims.Subject)
	}

	fullName := user.FirstName + " " + user.LastName
	return &model.User{
		ID:            claims.Subject,
		Email:         user.Email,
		Name:          &fullName,
		Picture:       nil,
		EmailVerified: false,
	}, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
