apiVersion: v1
kind: Secret
metadata:
  name: mysql-credentials
type: Opaque
data:
  username: YWRtaW4=
  password: MWYyZDFlMmU2N2Rm
  host: MWYyZDFlMmU2N2Rm
  database: host
  port: MWYyZDFlMmU2N2Rm
