name: dev
variables:
  - name: access_token
    value: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhNTQxMDFiYS0xOTA1LTRiM2ItOTYxNC1iYTIyNjNiNjgyNDMiLCJhdWQiOlsibG9jYWwiXSwiZXhwIjoxNzc5NDUzMjYxfQ.plf59elJT_LFFzpMeOsktsu3n_O72uyOuJmAFKIYke7FUEei-QcUoUTMJVDoCfxFPvgND_z-2FzeDXACX40zcXkMEAsKEigHg1NIh46Defv9AGEH8xnxH_7Q1TmbFkEhIPTGIvAPU-BcqX_txnKoFkKOY3TXFPhJKQN4x3shULrZrSUSsMaHfXbDlLaV8QvzkF6MHsWVrYElRMulXDGA-VHL-wLr-xdYF3DLFjUUEVk-srM3EooWpmaFwR5_IkhKWG2Jcfm1XbpvyPIG8qbC4OnWasSA1c2vrnLhqGzJUtGmIZ7C2kEJPeckWxTFhBd-w5Rx5bSdQkqtq-pdp4nMvg
