name: dev
variables:
  - name: access_token
    value: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJvcGVuIHNvdXJjZSIsInN1YiI6ImE1NDEwMWJhLTE5MDUtNGIzYi05NjE0LWJhMjI2M2I2ODI0MyIsImF1ZCI6WyJsb2NhbCJdLCJleHAiOjE3Nzk1MzY2NTB9.Il1WcPHmtnxM_VgmSxMujtKfKvw04ApFp6YYlJ7UEmCLlQrtCyNFHD5onYEdiEHDo0CGhTLTG80J9g61DWPMTsO1IahMTi-tlUnjLGpuRsChLWwqG0_aQuqIMSFMX8wYEGJJCrBZkl1M2ncI7NsjdTw3AlHpJuGu52sg0tc-J8yh9_LfSXCeg_TaDpc_osIzZJfz8Ag73vGnjkMnj_9gC5pp2rV_NhoA_6c90LsLZKfuaac5esWBcUeOMigkHLfIs-kF-UETvGF5fwF-mQ4Tp_OzbIIZpmx4LaARW5ClNbkatzcX4yAoIpo9sRTnsorNpjXiJcfsAbnFOvaDGIyNBA
