name: dev
variables:
  - name: access_token
    value: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJvcGVuIHNvdXJjZSIsInN1YiI6ImE1NDEwMWJhLTE5MDUtNGIzYi05NjE0LWJhMjI2M2I2ODI0MyIsImF1ZCI6WyJsb2NhbCJdLCJleHAiOjE3Nzk0MzkwNDJ9.fuchjux_L2oHwuAZM4ICwZEhKVZPRuhtodKLeXmkHzwOW8A3c-DGix1NWfp5VzlO2A2CW_MoHeto7rC0SH2XOWqemK2NhLjmyaLubB3Rkn0Kr2Lvsqj8U8efKuxbSXikFA1MQFLs3tyuchjaHyzQOU2GoyIZhOrwfGx0J_RUmzFaJV9K3L-VP3oYyjTUaU8gseg4hhvTdCATVQt4OdO84QZp5k_tBFesTM5-0AMKxLtyZ6SDYol2okJEWOwIWF1rJkrUMP91EYiyUDyPBspjpJayUoZ5FihrN9ZUjAJBlGvhsGEb9lSLrbVfnBOAkN1WEIrWo8Mv1gr4zarRs-KPIg
