// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.25.3
// source: app/auth-api/gRPC/identity.proto

package identity

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message containing the user's name.
type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         *string                `protobuf:"bytes,1,req,name=email" json:"email,omitempty"`
	Password      *string                `protobuf:"bytes,2,req,name=password" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_app_auth_api_gRPC_identity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_auth_api_gRPC_identity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_app_auth_api_gRPC_identity_proto_rawDescGZIP(), []int{0}
}

func (x *LoginRequest) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil && x.Password != nil {
		return *x.Password
	}
	return ""
}

// The response message containing the greetings
type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *int32                 `protobuf:"varint,1,req,name=status" json:"status,omitempty"`
	AccessToken   *string                `protobuf:"bytes,2,opt,name=access_token,json=accessToken" json:"access_token,omitempty"`
	Expiry        *string                `protobuf:"bytes,3,opt,name=expiry" json:"expiry,omitempty"`
	TokenType     *string                `protobuf:"bytes,4,opt,name=token_type,json=tokenType" json:"token_type,omitempty"`
	LastRefresh   *string                `protobuf:"bytes,5,opt,name=last_refresh,json=lastRefresh" json:"last_refresh,omitempty"`
	TokenTtl      *int32                 `protobuf:"varint,6,opt,name=token_ttl,json=tokenTtl" json:"token_ttl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_app_auth_api_gRPC_identity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_auth_api_gRPC_identity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_app_auth_api_gRPC_identity_proto_rawDescGZIP(), []int{1}
}

func (x *LoginResponse) GetStatus() int32 {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return 0
}

func (x *LoginResponse) GetAccessToken() string {
	if x != nil && x.AccessToken != nil {
		return *x.AccessToken
	}
	return ""
}

func (x *LoginResponse) GetExpiry() string {
	if x != nil && x.Expiry != nil {
		return *x.Expiry
	}
	return ""
}

func (x *LoginResponse) GetTokenType() string {
	if x != nil && x.TokenType != nil {
		return *x.TokenType
	}
	return ""
}

func (x *LoginResponse) GetLastRefresh() string {
	if x != nil && x.LastRefresh != nil {
		return *x.LastRefresh
	}
	return ""
}

func (x *LoginResponse) GetTokenTtl() int32 {
	if x != nil && x.TokenTtl != nil {
		return *x.TokenTtl
	}
	return 0
}

var File_app_auth_api_gRPC_identity_proto protoreflect.FileDescriptor

const file_app_auth_api_gRPC_identity_proto_rawDesc = "" +
	"\n" +
	" app/auth-api/gRPC/identity.proto\"@\n" +
	"\fLoginRequest\x12\x14\n" +
	"\x05email\x18\x01 \x02(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x02(\tR\bpassword\"\xc1\x01\n" +
	"\rLoginResponse\x12\x16\n" +
	"\x06status\x18\x01 \x02(\x05R\x06status\x12!\n" +
	"\faccess_token\x18\x02 \x01(\tR\vaccessToken\x12\x16\n" +
	"\x06expiry\x18\x03 \x01(\tR\x06expiry\x12\x1d\n" +
	"\n" +
	"token_type\x18\x04 \x01(\tR\ttokenType\x12!\n" +
	"\flast_refresh\x18\x05 \x01(\tR\vlastRefresh\x12\x1b\n" +
	"\ttoken_ttl\x18\x06 \x01(\x05R\btokenTtl22\n" +
	"\bIdentity\x12&\n" +
	"\x05Login\x12\r.LoginRequest\x1a\x0e.LoginResponseB\tZ\a../gRPC"

var (
	file_app_auth_api_gRPC_identity_proto_rawDescOnce sync.Once
	file_app_auth_api_gRPC_identity_proto_rawDescData []byte
)

func file_app_auth_api_gRPC_identity_proto_rawDescGZIP() []byte {
	file_app_auth_api_gRPC_identity_proto_rawDescOnce.Do(func() {
		file_app_auth_api_gRPC_identity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_app_auth_api_gRPC_identity_proto_rawDesc), len(file_app_auth_api_gRPC_identity_proto_rawDesc)))
	})
	return file_app_auth_api_gRPC_identity_proto_rawDescData
}

var file_app_auth_api_gRPC_identity_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_app_auth_api_gRPC_identity_proto_goTypes = []any{
	(*LoginRequest)(nil),  // 0: LoginRequest
	(*LoginResponse)(nil), // 1: LoginResponse
}
var file_app_auth_api_gRPC_identity_proto_depIdxs = []int32{
	0, // 0: Identity.Login:input_type -> LoginRequest
	1, // 1: Identity.Login:output_type -> LoginResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_app_auth_api_gRPC_identity_proto_init() }
func file_app_auth_api_gRPC_identity_proto_init() {
	if File_app_auth_api_gRPC_identity_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_auth_api_gRPC_identity_proto_rawDesc), len(file_app_auth_api_gRPC_identity_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_auth_api_gRPC_identity_proto_goTypes,
		DependencyIndexes: file_app_auth_api_gRPC_identity_proto_depIdxs,
		MessageInfos:      file_app_auth_api_gRPC_identity_proto_msgTypes,
	}.Build()
	File_app_auth_api_gRPC_identity_proto = out.File
	file_app_auth_api_gRPC_identity_proto_goTypes = nil
	file_app_auth_api_gRPC_identity_proto_depIdxs = nil
}
