// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type LoginInput struct {
	Email    *string `json:"email,omitempty"`
	Password *string `json:"password,omitempty"`
}

type LoginResponse struct {
	Status      *int    `json:"status,omitempty"`
	AccessToken *string `json:"accessToken,omitempty"`
	Expiry      *string `json:"expiry,omitempty"`
	TokenType   *string `json:"tokenType,omitempty"`
	LastRefresh *string `json:"lastRefresh,omitempty"`
	TokenTTL    *int    `json:"tokenTTL,omitempty"`
}

type Mutation struct {
}

type Query struct {
}

type RegisterInput struct {
	FirstName string  `json:"firstName"`
	LastName  string  `json:"lastName"`
	Email     string  `json:"email"`
	Password  string  `json:"password"`
	Company   *string `json:"company,omitempty"`
	PostCode  *string `json:"postCode,omitempty"`
	Terms     bool    `json:"terms"`
}

type RegisterResponse struct {
	ID        *string `json:"id,omitempty"`
	FirstName *string `json:"firstName,omitempty"`
	LastName  *string `json:"lastName,omitempty"`
	Email     *string `json:"email,omitempty"`
	Company   *string `json:"company,omitempty"`
	PostCode  *string `json:"postCode,omitempty"`
	Terms     *bool   `json:"terms,omitempty"`
	CreatedAt *string `json:"createdAt,omitempty"`
}

type RoleResponse struct {
	UserID string `json:"userId"`
	Role   Role   `json:"role"`
}

type User struct {
	ID            string  `json:"id"`
	Email         string  `json:"email"`
	Name          *string `json:"name,omitempty"`
	Picture       *string `json:"picture,omitempty"`
	EmailVerified bool    `json:"emailVerified"`
}

type Role string

const (
	RoleAdmin Role = "ADMIN"
	RoleUser  Role = "USER"
)

var AllRole = []Role{
	RoleAdmin,
	RoleUser,
}

func (e Role) IsValid() bool {
	switch e {
	case RoleAdmin, RoleUser:
		return true
	}
	return false
}

func (e Role) String() string {
	return string(e)
}

func (e *Role) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Role(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Role", str)
	}
	return nil
}

func (e Role) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Role) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Role) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
