// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type LoginInput struct {
	Email    *string `json:"email,omitempty"`
	Password *string `json:"password,omitempty"`
}

type LoginResponse struct {
	Status      *int    `json:"status,omitempty"`
	AccessToken *string `json:"accessToken,omitempty"`
	Expiry      *string `json:"expiry,omitempty"`
	TokenType   *string `json:"tokenType,omitempty"`
	LastRefresh *string `json:"lastRefresh,omitempty"`
	TokenTTL    *int    `json:"tokenTTL,omitempty"`
}

type Mutation struct {
}

type Query struct {
}

type User struct {
	ID            string  `json:"id"`
	Email         string  `json:"email"`
	Name          *string `json:"name,omitempty"`
	Picture       *string `json:"picture,omitempty"`
	EmailVerified bool    `json:"emailVerified"`
}
